=head1 NAME

dh-dist-zilla - debhelper add-on to run dzil (Dist::Zilla) during build

=head1 DESCRIPTION

The dh-dist-zilla package provides a sequence addon for debhelper 7
and above which can be used in the following two ways:

In C<debian/rules> since debhelper 7:

    #!/usr/bin/make -f
    export DH_VERBOSE=1
    %:
        dh $@ --with dist-zilla

Since debhelper 11.4 alternatively also just in C<debian/control>:

    Build-Depends: dh-sequence-dist-zilla

Both variants will call C<dzil build> prior to C<dh_auto_configure>,
C<dzil clean> before C<dh_clean> and will add the option C<-D
I<build-directory>> to C<dh_auto_configure>, C<dh_auto_build>,
C<dh_auto_install>, and C<dh_auto_test>.

=head2 How to generate the .orig.tar.xz "upstream" tar-ball

A `debian/rules` file as mentioned above also provides a
`get-orig-source` target to generate a source tar ball which contains
the minimal necessary contents (compared to the contents of tar-ball
for CPAN which would require some additional, generated meta data
files):

    make -f debian/rules get-orig-source

Or if your `debian/rules` file is executable, you can also just call
it like this:

    debian/rules get-orig-source

If you want to type even less, there's also a `origtar` alias (named
after the `origtargz` script from the `devscripts` package) for this
target:

    debian/rules origtar

=head1 SEE ALSO

L<debhelper(7)>, L<dh(1)>, L<dzil(1)>, L<dh_dzil_build(1)>,
L<dh_dzil_clean(1)>, L<dh_dist_zilla_origtar(1)>

=head1 AUTHOR

Elmar Heeb <elmar@heebs.ch> and Axel Beckert <abe@debian.org>
